version: "3.2"
services:
  db:
    build: .
    ports:
     - "5432:5432"
    restart: on-failure
    environment: 
     - TZ=Asia/Tokyo
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=testdb
     - PGDATA=/var/lib/postgresql/data/pgdata
     - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
     - ./ini:/docker-entrypoint-initdb.d
     - ./database:/var/lib/postgresql
    tty: true
